site_name: Notes of Phaser 3
nav:
- Home: index.md
- System:
    - Game:
        - Game: game.md
        - Main loop: mainloop.md
    - Scene:
        - Scene: scene.md
        - Scene manager: scenemanager.md
    - Snapshot: snapshot.md
- Loader:
    - Loader: loader.md
    - Webfont loader: webfontloader.md
    - Await loader:  awaitloader.md
- Game object:
    - Game object: gameobject.md
    - Sprite:
        - Single image:
            - Image: image.md
            - Sprite: sprite.md
            - Quad: quad.md    
        - Multiple images: 
            - Blitter: blitter.md
            - Particles: particles.md        
            - Tile sprite: tilesprite.md
        - Texture: texture.md
    - Text:
        - Canvas text:
            - Text: text.md
            - BBCode Text: bbcodetext.md
            - Tag Text: tagtext.md
        - Bitmap text:
            - Static bitmap text: bitmaptext.md
            - Dynamic bitmap text: dynamicbitmaptext.md
        - Behaviors:
            - Typing: texttyping.md    
            - Page: textpage.md
    - Graphics:
        - Graphics: graphics.md
        - Render texture: rendertexture.md
        - Shape:
            - Rectangle: shape-rectangle.md
            - Circle: shape-circle.md
            - Arc: shape-arc.md
            - Line: shape-line.md
            - Ellipse: shape-ellipse.md
            - Polygon: shape-polygon.md
            - Curve: shape-curve.md
            - Star: shape-star.md
            - Triangle: shape-triangle.md
            - Grid: shape-grid.md
            - Iso box: shape-isobox.md
            - Iso triangle: shape-isotriangle.md
            - Round Rectangle: shape-roundrectangle.md
        - Canvas: canvas.md        
    - Tile map:
        - Tile map: tilemap.md
    - Container:
        - Container: container.md
        - Container Lite: containerlite.md
        - Group: group.md        
        - Grid table: gridtable.md
        - UI:
            - Sizer: ui-sizer.md
            - Grid sizer: ui-gridsizer.md
            - Label: ui-label.md
            - Text box: ui-textbox.md
            - Dialog: ui-dialog.md
            - Grid table: ui-gridtable.md
            - Tabs: ui-tabs.md
            - Menue: ui-menu.md
    - Zone: zone.md
    - DOM element:
        - DOM element: domelement.md
    - Behaviors:
        - Actions:
            - Group actions: groupactions.md
            - Quad/Hexagon grid align: gridalign.md    
        - Move to: moveto.md
        - Rotate to: rotateto.md
        - Flash: flash.md
        - Fade out destroy: fadeoutdestroy.md
        - Pop up: popup.md
        - Scale down destroy: scaledowndestroy.md
        - Path follower: pathfollower.md
        - Interception: interception.md
        - Arcade:
            - World: arcade-world.md
            - Body: arcade-body.md
            - Game object: arcade-gameobject.md
            - 8 direction: eightdirection.md
            - Bullet: bullet.md
    - Display:
        - Mask: mask.md
- Input:
    - Input: input.md
    - Touch:    
        - Touch events: touchevents.md
        - Cursor: cursor.md
        - Button: button.md
        - Drag: drag.md
        - Slider: slider.md
        - Scroller: scroller.md
        - Virtual joystick: virtualjoystick.md
    - Keyboard:
        - Keyboard events: keyboardevents.md
- Audio:
    - Audio: audio.md
    - Volume fading: fadevolume.md
- Camera:
    - Camera: camera.md
    - Filters:
        - Swirl: swirlpipeline.md
        - Pixelation: pixelationpipeline.md
- Tween: tween.md        
- Logic:
    - Event emitter: eventemitter3.md
    - Run commands:
      - Run commands: runcommands.md
      - Sequence: sequence.md
      - CSV scenario: csvscenario.md
      - TCRP:
          - Recoder: tcrp-recoder.md
          - Player: tcrp-player.md
    - FSM: fsm.md
    - Wait events: waitevents.md
    - CSV table:
        - Conditions table: conditionstable.md
- Data:
    - Data manager: 
        - Built-in data: datamanager.md
        - Restorable data: restorabledata.md    
    - Set: structs-set.md
    - Array:
        - Filter/Map: array-filter.md
        - Random: random-array.md
        - Number array: create-number-array.md
    - CSV:
        - CSV to array: csvtoarray.md
        - CSV to hash table: csvtohashtable.md
    - Database:
        - LokiJs: lokijs.md
- Math:
    - Max, min:
        - Interpolation: interpolation.md
        - Percentage: percentage.md
        - Clamp: clamp.md
        - Wrap: wrap.md
    - Distance: distance.md
    - Angle: angle.md
    - Random:
        - Random number: random.md
        - Gashapon: gashapon.md
    - Color: color.md
    - Vector:
        - Vector2: vector2.md
    - Geometry:
        - Circle: geom-circle.md
        - Rectangle: geom-rectangle.md
        - Line: geom-line.md
        - Point: geom-point.md
        - Ellipse: geom-ellipse.md
        - Triangle: geom-triangle.md        
        - Polygon: geom-polygon.md
        - Rhombus: geom-rhombus.md
        - Hexagon: geom-hexagon.md
    - Path: path.md
- String:
    - Format:
        - Format: format.md
        - Mustache: mustache.md
    - Pad: pad.md
    - Capitalizes first: capitalizes-first.md
    - Reverse: reverse-string.md
    - LZ string: lzstring.md
    - XOR: xor.md
    - UUID: uuid.md
- Time:
    - Date: date.md
    - Timer: timer.md
    - Timeline: timeline.md    
    - Clock: clock.md
    - Life time: lifetime.md
- Board:
    - Board: board.md
    - Grid:    
        - Quad: board-quadgrid.md
        - Hexagon: board-hexagongrid.md
    - Chess data: board-chessdata.md
    - Shape: board-shape.md
    - Move to: board-moveto.md
    - Path finder: board-pathfinder.md
    - Match: board-match.md
    - Hexagon map: board-hexagonmap.md
    - Mini board:
        - Mini board: board-miniboard.md
    - Bejeweled: board-bejeweled.md
- Storage:
    - Offline:
        - Key-value pairs:
            - LocalStorage: localstorage.md
            - LocalForage: localforage.md
    - Online:
        - Firebase:
            - Authentication: firebase-auth.md
            - Firestore: firebase-firestore.md
            - Storage: firebase-storage.md


extra_javascript:
- js/mermaid/mermaid.min.js
- js/umlconvert.js 

theme:
    name: 'material'
    logo:
        icon: 'memory'    
    favicon: 'images/logo.svg'
    palette:
        primary: 'blue'
        accent: 'blue'

site_author: rexrainbow
site_url: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/index.html

repo_name: 'phaser3-rex-notes'
repo_url: 'https://github.com/rexrainbow/phaser3-rex-notes'

extra:
    social:
        - type: 'twitter'
          link: https://twitter.com/rexrainbow
        - type: github
          link: https://github.com/rexrainbow/


google_analytics:
    - 'UA-119804412-1'
    - 'auto'      

markdown_extensions:
- admonition
- codehilite(guess_lang=false,linenums=false)
- toc(permalink=true)
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences: [
       {name: mermaid, class: mermaid}
    ]
- pymdownx.tasklist
- pymdownx.tilde