site_name: Notes of Phaser 3
pages:
- Home: index.md
- System:
    - Game: game.md
    - Scene manager: scenemanager.md
    - Scene: scene.md
- Input:
    - Input: input.md
    - Touch:    
        - Touch events: touchevents.md
        - Cursor: cursor.md
        - Drag: drag.md
        - Slider: slider.md
        - Touch to cursorKeys: touchcursor.md
    - Keyboard:
        - Keyboard events: keyboardevents.md
- Loader:
    - Loader: loader.md
    - Webfont loader: webfontloader.md    
- Game object:
    - Game object: gameobject.md
    - Sprite:
        - Image: image.md
        - Blitter: blitter.md
    - Text:
        - Text: text.md
        - BBCode Text: bbcodetext.md
        - Tag Text: tagtext.md
        - Typing: texttyping.md    
        - Page: textpage.md
    - Canvas:
        - Graphics: graphics.md
        - Canvas: canvas.md
    - Tile map:
        - Tile map: tilemap.md
    - Container:
        - Container: container.md        
        - Group: group.md
        - Group actions: groupactions.md
        - Grid table: gridtable.md
- Time:
    - Date: date.md
    - Timer: timer.md
    - Timeline: timeline.md    
    - Clock: clock.md
- Behavior:
    - Tween: 
       - Tween: tween.md
       - Fade out destroy: fadeoutdestroy.md
    - Arcade:
        - Physics: arcade.md
- Audio:
    - Audio: audio.md
    - Volume fading: fadevolume.md
- Data:
    - Data manager: datamanager.md
    - Array: array.md
    - CSV:
        - CSV to array: csvtoarray.md
        - CSV to hash table: csvtohashtable.md
    - Database:
        - LokiJs: lokijs.md    
- Logic:
    - Event emitter: eventemitter3.md
    - Run commands:
      - Run commands: runcommands.md
      - Sequence: sequence.md
      - CSV scenario: csvscenario.md
      - TCRP:
          - Recoder: tcrprecoderplugin.md
          - Player: tcrpplayerplugin.md
    - FSM: fsm.md
- Camera:
    - Camera: camera.md
- Math:
    - Random:
        - Random number: random.md
        - Gashapon: gashapon.md
- String:
    - Format: format.md
    - Mustache: mustache.md
    - LZ string: lzstringplugin.md
    - XOR: xor.md
- Storage:
    - Offline:
        - Key-value pairs:
            - LocalStorage: localstorage.md
            - LocalForage: localforage.md


extra_javascript:
- js/mermaid/mermaid.min.js
- js/umlconvert.js 

theme:
    name: 'material'
    logo: 'images/logo.svg'
    palette:
        primary: 'blue'
        accent: 'blue'

site_author: rexrainbow
site_url: https://rexrainbow.github.io/phaser3-rex-notes/docs/site/index.html

extra:
    social:
        - type: github
          link: https://github.com/rexrainbow/
    disqus: 'notes-of-phaser3'

google_analytics:
    - 'UA-119804412-1'
    - 'auto'      

use_directory_urls: false
    
markdown_extensions:
- admonition
- codehilite(guess_lang=false,linenums=false)
- toc(permalink=true)
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences: [
       {name: mermaid, class: mermaid}
    ]
- pymdownx.tasklist
- pymdownx.tilde