site_name: Notes of Phaser 3
theme: 'material'

pages:
- Home: index.md
- System:
    - Game: game.md
    - Scene manager: scenemanager.md
    - Scene: scene.md
- Input:
    - Touch events: touchevents.md
    - Keyboard events: keyboardevents.md
    - Drag: dragplugin.md
    - Drag to cursorKeys: dragcursorplugin.md
- Loader:
    - Loader: loader.md
    - Webfont loader: webfontloader.md    
- Game object:
    - Game object: gameobject.md
    - Sprite:
        - Image: image.md
    - Text:
        - Text: text.md
        - Typing: texttypingplugin.md    
        - Page: textpageplugin.md
    - Canvas:
        - Graphics: graphics.md
        - Canvas: canvas.md
    - Group:
        - Group: group.md
        - Group actions: groupactions.md
- Time:
    - Date: date.md
    - Timer: timer.md
    - Timeline: timeline.md    
    - Clock: clockplugin.md
- Behavior:
    - Tween: 
       - Tween: tween.md
    - Arcade:
        - Physics: arcade.md
- Data:
    - Data manager: datamanager.md
    - Array: array.md
    - CSV to array: csvtoarray.md
- Logic:
    - Event emitter: eventemitter3.md
    - Run commands: runcommands.md
    - TCRP:
        - Recoder: tcrprecoderplugin.md
        - Player: tcrpplayerplugin.md
- Camera:
    - Camera: camera.md
- Math:
    - Random:
        - Gashapon: gashaponplugin.md
- String:
    - Format: format.md
    - Mustache: mustache.md
    - LZ string: lzstringplugin.md
    - XOR: xorplugin.md

extra_javascript:
- js/mermaid/mermaid.min.js
- js/umlconvert.js 

use_directory_urls: false
    
markdown_extensions:
- admonition
- codehilite(guess_lang=false,linenums=false)
- toc(permalink=true)
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences: [
       {name: mermaid, class: mermaid}
    ]
- pymdownx.tasklist
- pymdownx.tilde